export const GET_CHARACTERS = 'GET_CHARACTERS';
export const FILTER_CHARACTERS = 'FILTER_CHARACTERS';
export const TYPE_FILTER = 'TYPE_FILTER';
export const WEAPON_FILTER = 'WEAPON_FILTER';
export const ACCESSORY_FILTER = 'ACCESSORY_FILTER';
export const LS_FILTER = 'LS_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
